sudo: required
services:
    - docker
language: python
matrix:
    include:
        -   env: TOXENV=py36
            python: 3.6
install: pip install coveralls tox
script:
    - tox
    - make itest_trusty
    - make itest_xenial
    - make itest_bionic
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
